/**
 * ---------------------------------------------------------------------------
 *  GLOBAL SITE CONFIGURATION
 * ---------------------------------------------------------------------------
 *  Everything in this file is imported across the whole site. Change a value
 *  here and it updates everywhere — navigation, SEO defaults, affiliate links,
 *  disclosure copy, footer, structured data.
 * ---------------------------------------------------------------------------
 */

export const SITE = {
  /** Brand name used in the header, <title> suffix and JSON-LD. */
  name: 'HostScope',
  /** Short tagline used in the hero and OG description fallbacks. */
  tagline: 'Independent Hostinger research, real prices, and beginner-friendly tutorials',
  /** Production URL — must match the `site` value in astro.config.mjs. */
  url: 'https://hostscope.io',
  /** Default meta description (max ~155 chars for best SERP display). */
  description:
    'Hands-on Hostinger reviews, a live pricing matrix for every plan, working promo codes, and step-by-step hPanel tutorials — written by people who actually use it.',
  /** Default social share image (generated at build time by src/pages/og/). */
  defaultOgImage: '/og/default.png',
  /** Language + locale used for <html lang> and Open Graph. */
  lang: 'en',
  locale: 'en_US',
  /** Editorial team behind the site — powers E-E-A-T signals. */
  publisher: {
    name: 'HostScope Editorial',
    legalName: 'HostScope Media',
    email: 'hello@hostscope.io',
    address: 'Suite 2100, 1 Market Street, San Francisco, CA 94105',
  },
  /** When the pricing data across the site was last manually verified. */
  pricingVerified: '2026-09-17',
} as const;

/**
 * ---------------------------------------------------------------------------
 *  AFFILIATE / MONETISATION CONFIGURATION  ← single source of truth
 * ---------------------------------------------------------------------------
 *  Every outbound "Claim Deal" link on the site is generated by
 *  `affiliateUrl()` below. Change AFFILIATE.baseUrl once and the entire site
 *  (hundreds of buttons, cards, sticky bars, article CTAs) updates instantly.
 *
 *  Tracking parameters:
 *   - `offer_id` / `aff_id`  → required by the Hostinger affiliate network.
 *   - `sub_id`               → our own per-placement tracking token. It lets
 *                              you see inside the affiliate dashboard which
 *                              page or button actually produced the sale.
 *                              Set `subIdParam` to whatever your network
 *                              expects (sub_id, aff_sub, subid, …).
 *   - `utm_*`                → optional, for your own analytics platform.
 */
export const AFFILIATE = {
  /** Base affiliate destination — the ONLY place this URL should exist. */
  baseUrl: 'https://www.hostg.xyz/aff_c?offer_id=6&aff_id=109714',
  /** Affiliate/partner ID, surfaced in the disclosure copy. */
  affId: '109714',
  /** The query-string key used for our internal placement tracking. */
  subIdParam: 'sub_id',
  /** Append utm_* params for your own analytics. Set to false to disable. */
  useUtm: true,
  utmSource: 'hostscope',
  /**
   * Global coupon code shown in the sticky bar & coupon page.
   * This is the code the affiliate network actually honours at checkout.
   */
  defaultCoupon: '30OFF',
  /**
   * What `defaultCoupon` is worth, as a percentage off the order.
   * Displayed next to the code — keep it in sync with the network, because
   * quoting a bigger discount than the code delivers is a fast way to lose
   * trust (and to get a placement pulled).
   */
  couponDiscount: 10,
  /** Whether to render the affiliate disclosure banner above article bodies. */
  showDisclosure: true,
} as const;

/** Ready-made label for CTAs, e.g. "10% off with code 30OFF". */
export const COUPON_LABEL = `${AFFILIATE.couponDiscount}% off with code ${AFFILIATE.defaultCoupon}`;

/** Canonical outbound link. Prefer `affiliateUrl()` so you get sub-id tracking. */
export const AFFILIATE_URL = AFFILIATE.baseUrl;

export type AffiliatePlacement =
  | 'header-cta'
  | 'hero-primary'
  | 'hero-secondary'
  | 'pricing-matrix'
  | 'plan-card'
  | 'plan-detail-hero'
  | 'plan-detail-footer'
  | 'comparison-table'
  | 'coupon-page'
  | 'sticky-bar'
  | 'article-inline'
  | 'article-footer'
  | 'sidebar-widget'
  | 'tool-result'
  | 'footer-cta'
  | 'exit-intent'
  | 'home-section';

export interface AffiliateLinkOptions {
  /** Where on the site the click came from. Shows up as `sub_id`. */
  placement?: AffiliatePlacement | string;
  /** Optional campaign tag (e.g. a specific promo push). */
  campaign?: string;
  /** Optional plan slug the visitor was looking at. */
  plan?: string;
}

/**
 * Build a tracked Hostinger affiliate URL.
 *
 * @example
 * affiliateUrl({ placement: 'plan-card', plan: 'cloud-startup' })
 * // → https://www.hostg.xyz/aff_c?offer_id=6&aff_id=109714&sub_id=plan-card__cloud-startup
 */
export function affiliateUrl(options: AffiliateLinkOptions = {}): string {
  const { placement, campaign, plan } = options;
  let url: URL;
  try {
    url = new URL(AFFILIATE.baseUrl);
  } catch {
    return AFFILIATE.baseUrl;
  }

  // Build a compact, human-readable sub-id so the affiliate dashboard is
  // actually readable: "plan-card__cloud-startup__sep-deals"
  const parts = [placement, plan, campaign].filter(Boolean) as string[];
  if (parts.length) {
    const subId = parts
      .join('__')
      .toLowerCase()
      .replace(/[^a-z0-9_:-]+/g, '-')
      .slice(0, 120);
    url.searchParams.set(AFFILIATE.subIdParam, subId);
  }

  if (AFFILIATE.useUtm) {
    url.searchParams.set('utm_source', AFFILIATE.utmSource);
    url.searchParams.set('utm_medium', 'affiliate');
    url.searchParams.set('utm_campaign', campaign ?? placement ?? 'general');
  }

  return url.toString();
}

/** Convenience: the plain, untracked-looking link for the disclosure page. */
export const AFFILIATE_DISCLOSURE_URL = AFFILIATE_URL;

/* -------------------------------------------------------------------------- */
/*  NAVIGATION                                                                */
/* -------------------------------------------------------------------------- */

export interface NavChild {
  label: string;
  href: string;
  description?: string;
  badge?: string;
}

export interface NavItem {
  label: string;
  href: string;
  children?: NavChild[];
}

export const PRIMARY_NAV: NavItem[] = [
  {
    label: 'Pricing',
    href: '/pricing/',
    children: [
      { label: 'All Hostinger plans', href: '/pricing/', description: 'Every plan, every price, one matrix' },
      { label: 'Web & Cloud hosting', href: '/pricing/#web-cloud', description: 'Premium, Unlimited, Cloud Startup+' },
      { label: 'VPS hosting (KVM)', href: '/pricing/#vps', description: 'KVM 1, 2, 4 and 8 compared' },
      { label: 'Website Builder', href: '/plans/hostinger-ai-builder/', description: 'AI builder plans & credits' },
      { label: 'Cost calculator', href: '/tools/hosting-cost-calculator/', description: 'Work out your real 4-year cost', badge: 'Tool' },
    ],
  },
  {
    label: 'Plans',
    href: '/plans/',
    children: [
      { label: 'Premium', href: '/plans/premium/', description: 'Cheapest way to start' },
      { label: 'Unlimited', href: '/plans/unlimited/', description: 'Best value overall', badge: 'Best value' },
      { label: 'Cloud Startup', href: '/plans/cloud-startup/', description: '4 cores, 4 GB RAM' },
      { label: 'Cloud Professional', href: '/plans/cloud-professional/', description: '5 cores, 6 GB RAM' },
      { label: 'KVM 2 VPS', href: '/plans/kvm-2/', description: 'The VPS sweet spot' },
      { label: 'Compare every plan', href: '/plans/', description: 'Side-by-side spec tables' },
    ],
  },
  {
    label: 'Reviews',
    href: '/category/review/',
    children: [
      { label: 'Hostinger review 2026', href: '/blog/hostinger-review/', description: 'Our full 30-day test' },
      { label: 'Is Hostinger good?', href: '/blog/is-hostinger-good/', description: 'Honest pros & cons' },
      { label: 'Hostinger vs Bluehost', href: '/compare/hostinger-vs-bluehost/' },
      { label: 'Hostinger vs SiteGround', href: '/compare/hostinger-vs-siteground/' },
      { label: 'All comparisons', href: '/compare/' },
    ],
  },
  {
    label: 'Tutorials',
    href: '/category/tutorial/',
    children: [
      { label: 'How to buy Hostinger', href: '/blog/how-to-buy-hostinger-hosting/' },
      { label: 'Connect your domain', href: '/blog/how-to-point-a-domain-to-hostinger/' },
      { label: 'Install WordPress', href: '/blog/how-to-install-wordpress-on-hostinger/' },
      { label: 'Set up email', href: '/blog/hostinger-business-email-setup/' },
      { label: 'Fix 503 errors', href: '/blog/fix-hostinger-503-error/' },
    ],
  },
  {
    label: 'Deals',
    href: '/coupons/',
    children: [
      { label: 'Promo codes & deals', href: '/coupons/', badge: 'Updated weekly' },
      { label: 'Cheapest way to buy', href: '/blog/cheapest-way-to-buy-hostinger/' },
      { label: 'Renewal prices explained', href: '/blog/hostinger-renewal-prices-explained/' },
      { label: 'Black Friday guide', href: '/blog/hostinger-black-friday-deals/' },
    ],
  },
  { label: 'Plan finder', href: '/tools/plan-finder/' },
];

export const FOOTER_NAV: { title: string; links: NavChild[] }[] = [
  {
    title: 'Hostinger plans',
    links: [
      { label: 'Premium hosting', href: '/plans/premium/' },
      { label: 'Unlimited hosting', href: '/plans/unlimited/' },
      { label: 'Cloud Startup', href: '/plans/cloud-startup/' },
      { label: 'Cloud Professional', href: '/plans/cloud-professional/' },
      { label: 'Cloud Enterprise', href: '/plans/cloud-enterprise/' },
      { label: 'KVM 1 VPS', href: '/plans/kvm-1/' },
      { label: 'KVM 2 VPS', href: '/plans/kvm-2/' },
      { label: 'KVM 4 VPS', href: '/plans/kvm-4/' },
      { label: 'KVM 8 VPS', href: '/plans/kvm-8/' },
      { label: 'AI Website Builder', href: '/plans/hostinger-ai-builder/' },
    ],
  },
  {
    title: 'Popular guides',
    links: [
      { label: 'Hostinger review 2026', href: '/blog/hostinger-review/' },
      { label: 'Is Hostinger worth it?', href: '/blog/is-hostinger-good/' },
      { label: 'Cheapest way to buy', href: '/blog/cheapest-way-to-buy-hostinger/' },
      { label: 'How to buy Hostinger', href: '/blog/how-to-buy-hostinger-hosting/' },
      { label: 'hPanel beginner tour', href: '/blog/hpanel-beginner-guide/' },
      { label: 'Renewal prices explained', href: '/blog/hostinger-renewal-prices-explained/' },
      { label: 'How to get a refund', href: '/blog/hostinger-refund-policy/' },
      { label: 'Free domain: how it works', href: '/blog/hostinger-free-domain-guide/' },
    ],
  },
  {
    title: 'Fix it',
    links: [
      { label: '503 Service Unavailable', href: '/blog/fix-hostinger-503-error/' },
      { label: 'Website is slow', href: '/blog/hostinger-website-slow-fix/' },
      { label: 'Emails going to spam', href: '/blog/hostinger-email-going-to-spam/' },
      { label: 'SSL not working', href: '/blog/hostinger-ssl-not-working/' },
      { label: 'Domain not connecting', href: '/blog/how-to-point-a-domain-to-hostinger/' },
      { label: 'WordPress white screen', href: '/blog/fix-wordpress-white-screen-hostinger/' },
    ],
  },
  {
    title: 'Tools & data',
    links: [
      { label: 'Plan finder quiz', href: '/tools/plan-finder/' },
      { label: 'Hosting cost calculator', href: '/tools/hosting-cost-calculator/' },
      { label: 'Promo codes', href: '/coupons/' },
      { label: 'Comparisons hub', href: '/compare/' },
      { label: 'All tutorials', href: '/category/tutorial/' },
      { label: 'Deals archive', href: '/category/deals/' },
    ],
  },
  {
    title: 'About',
    links: [
      { label: 'About HostScope', href: '/about/' },
      { label: 'Editorial policy', href: '/editorial-policy/' },
      { label: 'How we test', href: '/how-we-test/' },
      { label: 'Affiliate disclosure', href: '/affiliate-disclosure/' },
      { label: 'Contact', href: '/contact/' },
      { label: 'Privacy policy', href: '/privacy/' },
      { label: 'Terms of use', href: '/terms/' },
    ],
  },
];

/* -------------------------------------------------------------------------- */
/*  ARTICLE TAXONOMY                                                          */
/* -------------------------------------------------------------------------- */

export const CATEGORIES = {
  review: { label: 'Reviews', description: 'Deep, hands-on testing of Hostinger plans and features.' },
  tutorial: { label: 'Tutorials', description: 'Step-by-step walkthroughs for hPanel, WordPress, domains and email.' },
  guide: { label: 'Buying guides', description: 'How to choose — and how to pay the least for the right plan.' },
  deals: { label: 'Deals & pricing', description: 'Working promo codes, discount windows and renewal maths.' },
  comparison: { label: 'Comparisons', description: 'Hostinger measured against the alternatives that matter.' },
  troubleshooting: { label: 'Troubleshooting', description: 'Fixes for the errors Hostinger users actually hit.' },
} as const;

export type CategoryKey = keyof typeof CATEGORIES;

export const CATEGORY_LIST = Object.entries(CATEGORIES).map(([key, value]) => ({
  key: key as CategoryKey,
  ...value,
}));

/* -------------------------------------------------------------------------- */
/*  TRUST / SOCIAL PROOF                                                      */
/* -------------------------------------------------------------------------- */

export const TRUST_STATS = [
  { value: '5M+', label: 'Hostinger customers worldwide' },
  { value: '178', label: 'Countries served' },
  { value: '99.9%', label: 'Published uptime guarantee' },
  { value: '30 days', label: 'Money-back guarantee' },
];

export const EDITORS = {
  'maya-ross': {
    name: 'Maya Ross',
    role: 'Lead hosting reviewer',
    bio: 'Maya has migrated more than 400 sites between hosts and spent the last six years benchmarking shared, cloud and VPS platforms for small businesses.',
    avatar: '/images/authors/maya-ross.svg',
  },
  'daniel-okafor': {
    name: 'Daniel Okafor',
    role: 'Technical editor',
    bio: 'Daniel is a systems engineer who runs a fleet of KVM boxes for client projects. He writes our VPS, performance and troubleshooting guides.',
    avatar: '/images/authors/daniel-okafor.svg',
  },
  'priya-nair': {
    name: 'Priya Nair',
    role: 'Ecommerce & WordPress editor',
    bio: 'Priya builds WooCommerce stores for independent brands and covers WordPress tooling, checkout performance and email deliverability.',
    avatar: '/images/authors/priya-nair.svg',
  },
} as const;

export type EditorKey = keyof typeof EDITORS;
